"use client";

import { useState } from "react";

type View = "home" | "case" | "commit" | "update" | "results" | "admin";

const intel = [
  { key: "margin", label: "Ekonomi unit", body: "Margin kontribusi turun dari 34% menjadi 21% dalam enam bulan. Penurunan terkonsentrasi pada tier gratis ongkir." },
  { key: "retention", label: "Retensi pelanggan", body: "Retensi 90 hari stabil di 42%. Retensi cohort tidak berubah di semua kanal akuisisi." },
  { key: "logistics", label: "Operasional fulfilment", body: "Rata-rata waktu pengiriman bertambah 0,6 hari. Surcharge carrier naik 18% pada periode yang sama." },
  { key: "market", label: "Posisi pasar", body: "Dua kompetitor kategori mulai menawarkan gratis ongkir di atas Rp350 ribu. Janji pengiriman yang mereka iklankan tidak berubah." },
  { key: "promo", label: "Aktivitas promosi", body: "Frekuensi diskon naik 27%. Pesanan dengan diskon memiliki margin kontribusi 12 poin lebih rendah." },
];
const scores = [["Seleksi informasi",86],["Pembingkaian masalah",82],["Penalaran kausal",78],["Pertimbangan komersial",88],["Pemikiran sistem",73],["Kualitas keputusan",84],["Pembaruan keyakinan",91],["Komunikasi",79]];

export default function Home() {
  const [view, setView] = useState<View>("home"); const [revealed, setRevealed] = useState<string[]>([]); const [query, setQuery] = useState(""); const [openIntel, setOpenIntel] = useState<string | null>(null); const [decision, setDecision] = useState(""); const [changed, setChanged] = useState<string | null>(null);
  const credits = 5 - revealed.length; const current = intel.find((i) => i.key === openIntel); const progress = view === "case" ? 1 : view === "commit" ? 2 : view === "update" ? 3 : view === "results" ? 4 : 0;
  function ask(question?: string) { const text = (question || query).toLowerCase(); const match = intel.find((item) => text.includes(item.key) || text.includes(item.label.split(" ")[0].toLowerCase())) || intel.find((item) => !revealed.includes(item.key)); if (!match || credits === 0) return; setRevealed([...revealed, match.key]); setOpenIntel(match.key); setQuery(""); }
  const shell = (content: React.ReactNode) => <main className="app-shell"><header className="topbar"><button className="wordmark" onClick={() => setView("home")}>THE CMO<br/><i>TEST</i></button><div className="top-meta">BY ADITYA BAYU <span>•</span> SESI AMAN</div><button className="admin-link" onClick={() => setView("admin")}>DASHBOARD PENILAI ↗</button></header>{view !== "home" && view !== "admin" && <div className="progress"><span>SIMULASI 01 / 13</span><div className="progress-line"><i style={{width: `${progress * 25}%`}} /></div><span>{progress === 1 ? "INVESTIGASI" : progress === 2 ? "KEPUTUSAN" : progress === 3 ? "PEMBARUAN" : progress === 4 ? "HASIL" : "BRIEF"}</span></div>}{content}</main>;

  if (view === "home") return shell(<><section className="hero"><div className="eyebrow">ASSESSMENT UNTUK MARKETING LEADERS <b>01—13</b></div><h1>THE CMO<br/><em>TEST</em></h1><div className="hero-bottom"><p><strong>by Aditya Bayu</strong><br/>Bukan tes pengetahuan atau personality test. Ini adalah standar untuk melihat bagaimana seorang pemimpin marketing memetakan masalah, mengajukan pertanyaan, dan mengambil keputusan saat informasi belum lengkap.</p><button className="primary" onClick={() => setView("case")}>MULAI TES <span>→</span></button></div></section><section className="principles"><div><span>0,7%</span><h3>Yang lolos sejauh ini</h3><p>Secara statistik, hanya 0,7% kandidat yang lolos. Ini bukan tes untuk mengonfirmasi apa yang sudah Anda ketahui.</p></div><div><span>01</span><h3>Kasus nyata, standar nyata</h3><p>Seluruh simulasi berangkat dari kasus nyata yang sudah saya selesaikan sendiri.</p></div><div><span>02</span><h3>Untuk pemimpin marketing</h3><p>Dibuat untuk menguji kandidat di level Head, VP, hingga C-level Marketing.</p></div></section></>);

  if (view === "admin") return shell(<section className="admin-page"><div className="admin-heading"><div><span className="eyebrow">KONSOL PENILAI · THE CMO TEST</span><h2>Standar<br/><em>Anda.</em></h2></div><button className="primary small">BUAT UNDANGAN <span>+</span></button></div><div className="stat-row">{[["24","KANDIDAT AKTIF"],["08","SELESAI MINGGU INI"],["78.4","MEDIAN CMO INDEX"],["4","ANTREAN REVIEW"]].map(([n,l])=><div className="stat" key={l}><strong>{n}</strong><span>{l}</span></div>)}</div><div className="admin-grid"><div className="panel candidates"><div className="panel-title">AKTIVITAS KANDIDAT <button>LIHAT SEMUA</button></div>{[["Nadia Putri","Simulasi 08 · Sedang berjalan","63%"],["Marcus Chen","Selesai · Menunggu review","100%"],["Sonia Rahman","Simulasi 03 · Sedang berjalan","24%"],["Arief Wijaya","Selesai · Terkalibrasi","100%"]].map((c)=><div className="candidate" key={c[0]}><b>{c[0]}</b><span>{c[1]}</span><i>{c[2]}</i></div>)}</div><div className="panel"><div className="panel-title">STANDAR ADITYA BAYU <button>UBAH</button></div><div className="benchmark"><strong>CMO<br/>OPERATOR</strong><span>CMO Index</span><b>86.2</b></div><p className="quiet">Dibentuk dari assessment referensi yang dikerjakan langsung oleh Aditya Bayu · Rubrik v1.4</p><button className="outline">BUKA PERPUSTAKAAN KASUS →</button></div></div><div className="audit-strip"><span>AKTIVITAS AUDIT TERBARU</span><b>Marcus Chen · Simulasi 04 dinilai oleh 3 evaluator</b><button>PERIKSA BUKTI →</button></div></section>);

  if (view === "results") return shell(<section className="results"><span className="eyebrow">TES SELESAI · AUDIT ID CMO-260730-018</span><h2>Profil<br/><em>operasi Anda.</em></h2><div className="result-grid"><div className="index"><span>CMO INDEX</span><strong>84<span>.6</span></strong><b>CMO OPERATOR</b><p>Pertimbangan komersial kuat, dengan disiplin tinggi dalam memperbarui keyakinan berdasarkan bukti.</p><div className="peer">KESESUAIAN DENGAN STANDAR <b>91%</b><span>PEER+</span></div></div><div className="scorecard">{scores.map(([label,score])=><div className="score" key={String(label)}><span>{label}</span><div><i style={{width:`${score}%`}} /></div><b>{score}</b></div>)}</div></div><div className="results-actions"><button className="outline" onClick={()=>setView("home")}>KEMBALI KE AWAL</button><button className="primary">UNDUH REKAM TES <span>↓</span></button></div></section>);

  if (view === "update") return shell(<section className="case-layout"><aside><span className="eyebrow">BUKTI BARU</span><h2>Kendala dari<br/><em>supplier.</em></h2><p>Setelah keputusan Anda dikunci, carrier memberi tahu bahwa harga surcharge bersifat kontraktual untuk dua kuartal ke depan.</p><div className="shock"><span>TERUNGKAP SETELAH KEPUTUSAN</span><b>Surcharge tidak dapat dinegosiasikan atau dihentikan sebelum Q3.</b></div></aside><section className="workspace"><span className="eyebrow">PEMBARUAN KEYAKINAN</span><h3>Apakah bukti ini mengubah<br/>keputusan Anda?</h3><div className="choice-grid"><button className={changed === "no" ? "selected" : ""} onClick={()=>setChanged("no")}>TIDAK — KEPUTUSAN TETAP<span>Akar masalah dan respons tetap valid.</span></button><button className={changed === "yes" ? "selected" : ""} onClick={()=>setChanged("yes")}>YA — SAYA AKAN UBAH<span>Kendala baru ini mengubah tindakan secara berarti.</span></button></div><label>JELASKAN PERTIMBANGAN ANDA<textarea placeholder="Jelaskan secara tepat apa yang berubah—atau mengapa tidak—beserta implikasinya." /></label><button className="primary end" disabled={!changed} onClick={()=>setView("results")}>KIRIM POSISI AKHIR <span>→</span></button></section></section>);

  if (view === "commit") return shell(<section className="commit"><div className="commit-title"><span className="eyebrow">REKAM KEPUTUSAN · TERKUNCI SETELAH DIKIRIM</span><h2>Ambil<br/><em>keputusannya.</em></h2><p>Anda sudah menginvestigasi {revealed.length} dari 5 jalur yang tersedia. Konteks tersisa tidak lagi tersedia setelah keputusan dikirim.</p></div><div className="form"><label>01 — DIAGNOSIS<textarea placeholder="Apa yang sebenarnya terjadi? Nyatakan masalah inti, bukan gejalanya." /></label><label>02 — KEPUTUSAN<textarea value={decision} onChange={e=>setDecision(e.target.value)} placeholder="Apa tindakan bisnis berikutnya? Buat spesifik." /></label><label>03 — PERTIMBANGAN<textarea placeholder="Hubungkan bukti, mekanisme, dan hasil komersial yang diharapkan." /></label><div className="form-split"><label>TINGKAT KEYAKINAN <div className="confidence"><input type="range" defaultValue="70"/><span>70%</span></div></label><label>FAKTOR PEMBALIK<input placeholder="Satu fakta yang akan mengubah keputusan saya" /></label></div><button className="primary end" disabled={!decision} onClick={()=>setView("update")}>KUNCI KEPUTUSAN <span>→</span></button></div></section>);

  return shell(<section className="case-layout"><aside><span className="eyebrow">SIMULASI 01 · 28 MENIT</span><h2>Margin yang<br/><em>tertekan.</em></h2><p>Vela, retailer home goods mid-market, mencatat pertumbuhan revenue 31% year-over-year. Namun operating margin turun tajam. CEO meminta rekomendasi sebelum rapat board berikutnya.</p><dl><div><dt>REVENUE</dt><dd>+31% YoY</dd></div><div><dt>OPERATING MARGIN</dt><dd className="negative">−13 pts</dd></div><div><dt>JENDELA KEPUTUSAN</dt><dd>14 hari</dd></div></dl><div className="rule"><b>TUGAS ANDA</b> Temukan apa yang penting. Anda dapat menginvestigasi lima jalur informasi sebelum mengambil keputusan.</div></aside><section className="workspace"><div className="workspace-top"><span className="eyebrow">RUANG INVESTIGASI</span><b>{credits} <small>KREDIT TERSISA</small></b></div><h3>Apa yang perlu<br/>Anda ketahui?</h3><div className="inquiry"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key === "Enter" && ask()} placeholder="Ajukan pertanyaan tentang bisnis…"/><button onClick={()=>ask()}>TANYAKAN →</button></div><div className="prompt-list"><span>JALUR INVESTIGASI TERSEDIA</span>{intel.map(item=><button key={item.key} disabled={revealed.includes(item.key) || credits===0} onClick={()=>ask(item.label)}>{revealed.includes(item.key) ? "✓" : "○"} {item.label}<i>{revealed.includes(item.key) ? "TERBUKA" : "MINTA"}</i></button>)}</div>{current && <div className="intel-card"><span>CASE FILE / {String(revealed.length).padStart(2,"0")}</span><button onClick={()=>setOpenIntel(null)}>×</button><h4>{current.label}</h4><p>{current.body}</p></div>}<button className="primary end" onClick={()=>setView("commit")}>LANJUT KE KEPUTUSAN <span>→</span></button></section></section>);
}
